title: My portfolio
email: albertperezdatsira@gmail.com
github_username: albeertito7
#theme: minima (default) -> to have new Jekyll site up running with zero configuration
#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-hacker
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-merlot
#theme: jekyll-theme-midnight
#theme: jekyll-theme-minimal
#theme: jekyll-theme-modernist
#theme: jekyll-theme-slate
#theme: jekyll-theme-tactile
#theme: jekyll-theme-time-machine
#theme: jekyll-swiss