title: Welcome to my portfolio 😊
email: albertperezdatsira@gmail.com
description: Personal portfolio by albeertito7
author: Albert Pérez Datsira
baseurl: ""
url: "https://albeertito7.github.io"

# Social profiles
github_username: albeertito7

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Jekyll built-in themes
#theme: minima (default) -> to have new Jekyll site up running with zero configuration
#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-hacker
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-merlot
#theme: jekyll-theme-midnight
#theme: jekyll-theme-minimal
#theme: jekyll-theme-modernist
#theme: jekyll-theme-slate
#theme: jekyll-theme-tactile
#theme: jekyll-theme-time-machine

# External themes
#theme: jekyll-swiss

exclude:
  - Notes.txt
  - README.*
  - Gemfile*
  - contact.md
  - blog.md
  - about.md


favicon: 😇